name: Build Website

on:  
  push:
    branches:
      - toucan

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0.3

    env:
      TOUCAN_REF: 1.0.0-beta.2

    steps:
      - name: "Cache: Toucan"
        id: cache-toucan
        uses: actions/cache@v4
        with:
          path: /toucan
          key: tool-${{ env.TOUCAN_REF }}
      
      - if: steps.cache-toucan.outputs.cache-hit != 'true'
        name: "Checkout: Toucan"
        uses: actions/checkout@v4
        with:
          repository: toucansites/toucan
          ref: ${{ env.TOUCAN_REF }}

      - if: steps.cache-toucan.outputs.cache-hit != 'true'
        name: "Build: Toucan"
        run: |
            swift build -c release --product toucan-cli
            cp .build/release/toucan-cli /toucan

      - name: "Checkout: Website"
        uses: actions/checkout@v4
  
      - name: "Build: Website"
        run: /toucan generate src docs

      - name: "Upload: Website"
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
